# Generated by Django 2.2.4 on 2019-09-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author2Book',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Book')),
            ],
        ),
    ]
