# Generated by Django 2.2.4 on 2019-09-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_author2book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author2Book',
        ),
    ]
