# Generated by Django 2.2.4 on 2019-09-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_authordetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authordetail',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
