# Generated by Django 2.2.4 on 2019-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20190901_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('dep', models.CharField(max_length=32)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('addr', models.CharField(max_length=32)),
            ],
        ),
    ]
