# Generated by Django 2.2.4 on 2019-10-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181108_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
