# Generated by Django 2.1.1 on 2018-11-06 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20181026_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='poll_count',
        ),
    ]
